### ISSUE TITLE
clarification regarding composer.json requirement

### ISSUE THREAD

**Issue by DanielRuf** [php/php-windows-builder#4]
I'm not sure why a `composer.json` file is needed for compiling PHP extensions written in pure C or C++.

I see what the `composer.json` code part does (get the needed PHP version), but that makes not much sense, because composer is (generally) not part of a C toolchain.

Normally you have config.w32 files as only config files.

https://github.com/DanielRuf/php-spx/actions/runs/10759187217/job/29835547179

**Comment by shivammathur** [comment]
Hi @DanielRuf 
composer.json is not required if you want to just use this action as in the workflow you can specify everything as inputs to the action.

It supports reading them from composer.json also as you might consider adding that to add support for the new pie tool.
https://github.com/php/pie/blob/main/docs/extension-maintainers.md
